### ISSUE TITLE
AttributeError in Local_Join_Counts

### ISSUE THREAD

**Issue by martinfleis** [pysal/esda#395]
While trying to get a reproducer for the component issue, I just ran into another one. This seems to be caused by scikit estimator's repr.

```py
import geopandas as gpd
from libpysal import graph
from esda import Join_Counts_Local
import sklearn

sklearn.__version__  # 1.7.2


elections = gpd.read_file(
    "https://martinfleischmann.net/sds/autocorrelation/data/cz_elections_2023.gpkg"
)
elections = elections.set_index("name")
knn = graph.Graph.build_knn(elections.centroid, k=2)
var = elections.PetrPavel > 50
Join_Counts_Local(knn).fit(var)
```

```py
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
File ~/dev/pysal/.pixi/envs/default/lib/python3.11/site-packages/IPython/core/formatters.py:1036, in MimeBundleFormatter.__call__(self, obj, include, exclude)
   1033     method = get_real_method(obj, self.print_method)
   1035     if method is not None:
-> [1036](https://file+.vscode-resource.vscode-cdn.net/Users/martin/dev/pysal/esda/~/dev/pysal/.pixi/envs/default/lib/python3.11/site-packages/IPython/core/formatters.py:1036)         return method(include=include, exclude=exclude)
   1037     return None
   1038 else:

File ~/dev/pysal/.pixi/envs/default/lib/python3.11/site-packages/sklearn/utils/_repr_html/base.py:151, in ReprHTMLMixin._repr_mimebundle_(self, **kwargs)
    149 output = {"text/plain": repr(self)}
    150 if get_config()["display"] == "diagram":
--> [151](https://file+.vscode-resource.vscode-cdn.net/Users/martin/dev/pysal/esda/~/dev/pysal/.pixi/envs/default/lib/python3.11/site-packages/sklearn/utils/_repr_html/base.py:151)     output["text/html"] = self._html_repr()
    152 return output

File ~/dev/pysal/.pixi/envs/default/lib/python3.11/site-packages/sklearn/utils/_repr_html/estimator.py:480, in estimator_html_repr(estimator)
    469 html_template = (
    470     f"<style>{style_with_id}</style>"
    471     f"<body>"
   (...)    476     '<div class="sk-container" hidden>'
    477 )
    479 out.write(html_template)
--> [480](https://file+.vscode-resource.vscode-cdn.net/Users/martin/dev/pysal/esda/~/dev/pysal/.pixi/envs/default/lib/python3.11/site-packages/sklearn/utils/_repr_html/estimator.py:480) _write_estimator_html(
    481     out,
    482     estimator,
    483     estimator.__class__.__name__,
    484     estimator_str,
    485     first_call=True,
    486     is_fitted_css_class=is_fitted_css_class,
    487     is_fitted_icon=is_fitted_icon,
    488 )
    489 with open(str(Path(__file__).parent / "estimator.js"), "r") as f:
    490     script = f.read()

File ~/dev/pysal/.pixi/envs/default/lib/python3.11/site-packages/sklearn/utils/_repr_html/estimator.py:386, in _write_estimator_html(out, estimator, estimator_label, estimator_label_details, is_fitted_css_class, is_fitted_icon, first_call, param_prefix)
    384 elif est_block.kind == "single":
    385     if hasattr(estimator, "_get_params_html"):
--> [386](https://file+.vscode-resource.vscode-cdn.net/Users/martin/dev/pysal/esda/~/dev/pysal/.pixi/envs/default/lib/python3.11/site-packages/sklearn/utils/_repr_html/estimator.py:386)         params = estimator._get_params_html()._repr_html_inner()
    387     else:
    388         params = ""

File ~/dev/pysal/.pixi/envs/default/lib/python3.11/site-packages/sklearn/base.py:312, in BaseEstimator._get_params_html(self, deep)
    308 ordered_out = {name: out[name] for name in init_default_params if name in out}
    309 ordered_out.update({name: out[name] for name in remaining_params})
    311 non_default_ls = tuple(
--> [312](https://file+.vscode-resource.vscode-cdn.net/Users/martin/dev/pysal/esda/~/dev/pysal/.pixi/envs/default/lib/python3.11/site-packages/sklearn/base.py:312)     [name for name, value in ordered_out.items() if is_non_default(name, value)]
    313 )
    315 return ParamsDict(ordered_out, non_default=non_default_ls)

File ~/dev/pysal/.pixi/envs/default/lib/python3.11/site-packages/sklearn/base.py:312, in <listcomp>(.0)
    308 ordered_out = {name: out[name] for name in init_default_params if name in out}
    309 ordered_out.update({name: out[name] for name in remaining_params})
    311 non_default_ls = tuple(
--> [312](https://file+.vscode-resource.vscode-cdn.net/Users/martin/dev/pysal/esda/~/dev/pysal/.pixi/envs/default/lib/python3.11/site-packages/sklearn/base.py:312)     [name for name, value in ordered_out.items() if is_non_default(name, value)]
    313 )
    315 return ParamsDict(ordered_out, non_default=non_default_ls)

File ~/dev/pysal/.pixi/envs/default/lib/python3.11/site-packages/sklearn/base.py:295, in BaseEstimator._get_params_html.<locals>.is_non_default(param_name, param_value)
    291 if isinstance(param_value, BaseEstimator) and type(param_value) is not type(
    292     init_default_params[param_name]
    293 ):
    294     return True
--> [295](https://file+.vscode-resource.vscode-cdn.net/Users/martin/dev/pysal/esda/~/dev/pysal/.pixi/envs/default/lib/python3.11/site-packages/sklearn/base.py:295) if not np.array_equal(
    296     param_value, init_default_params[param_name]
    297 ) and not (
    298     is_scalar_nan(init_default_params[param_name])
    299     and is_scalar_nan(param_value)
    300 ):
    301     return True
    303 return False

File ~/dev/pysal/.pixi/envs/default/lib/python3.11/site-packages/numpy/_core/numeric.py:2590, in array_equal(a1, a2, equal_nan)
   2588     return False
   2589 if not equal_nan:
-> [2590](https://file+.vscode-resource.vscode-cdn.net/Users/martin/dev/pysal/esda/~/dev/pysal/.pixi/envs/default/lib/python3.11/site-packages/numpy/_core/numeric.py:2590)     return builtins.bool((asanyarray(a1 == a2)).all())
   2592 if a1 is a2:
   2593     # nan will compare equal so an array will compare equal to itself.
   2594     return True

File ~/dev/pysal/libpysal/libpysal/graph/_set_ops.py:28, in SetOpsMixin.__eq__(self, other)
     27 def __eq__(self, other):  # ==
---> [28](https://file+.vscode-resource.vscode-cdn.net/Users/martin/dev/pysal/esda/~/dev/pysal/libpysal/libpysal/graph/_set_ops.py:28)     return self.equals(other)

File ~/dev/pysal/libpysal/libpysal/graph/_set_ops.py:182, in SetOpsMixin.equals(self, right)
    169 """
    170 Check that two graphs are identical. This reqiures them to have
    171 1. the same edge labels and node labels
   (...)    178 (focal, neighbor, weight) for the two graphs are the same.
    179 """
    180 try:
    181     pandas.testing.assert_series_equal(
--> [182](https://file+.vscode-resource.vscode-cdn.net/Users/martin/dev/pysal/esda/~/dev/pysal/libpysal/libpysal/graph/_set_ops.py:182)         self._adjacency, right._adjacency, check_dtype=False
    183     )
    184 except AssertionError:
    185     return False

AttributeError: 'NoneType' object has no attribute '_adjacency'---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
File ~/dev/pysal/.pixi/envs/default/lib/python3.11/site-packages/IPython/core/formatters.py:1036, in MimeBundleFormatter.__call__(self, obj, include, exclude)
   1033     method = get_real_method(obj, self.print_method)
   1035     if method is not None:
-> [1036](https://file+.vscode-resource.vscode-cdn.net/Users/martin/dev/pysal/esda/~/dev/pysal/.pixi/envs/default/lib/python3.11/site-packages/IPython/core/formatters.py:1036)         return method(include=include, exclude=exclude)
   1037     return None
   1038 else:

File ~/dev/pysal/.pixi/envs/default/lib/python3.11/site-packages/sklearn/utils/_repr_html/base.py:151, in ReprHTMLMixin._repr_mimebundle_(self, **kwargs)
    149 output = {"text/plain": repr(self)}
    150 if get_config()["display"] == "diagram":
--> [151](https://file+.vscode-resource.vscode-cdn.net/Users/martin/dev/pysal/esda/~/dev/pysal/.pixi/envs/default/lib/python3.11/site-packages/sklearn/utils/_repr_html/base.py:151)     output["text/html"] = self._html_repr()
    152 return output

File ~/dev/pysal/.pixi/envs/default/lib/python3.11/site-packages/sklearn/utils/_repr_html/estimator.py:480, in estimator_html_repr(estimator)
    469 html_template = (
    470     f"<style>{style_with_id}</style>"
    471     f"<body>"
   (...)    476     '<div class="sk-container" hidden>'
    477 )
    479 out.write(html_template)
--> [480](https://file+.vscode-resource.vscode-cdn.net/Users/martin/dev/pysal/esda/~/dev/pysal/.pixi/envs/default/lib/python3.11/site-packages/sklearn/utils/_repr_html/estimator.py:480) _write_estimator_html(
    481     out,
    482     estimator,
    483     estimator.__class__.__name__,
    484     estimator_str,
    485     first_call=True,
    486     is_fitted_css_class=is_fitted_css_class,
    487     is_fitted_icon=is_fitted_icon,
    488 )
    489 with open(str(Path(__file__).parent / "estimator.js"), "r") as f:
    490     script = f.read()

File ~/dev/pysal/.pixi/envs/default/lib/python3.11/site-packages/sklearn/utils/_repr_html/estimator.py:386, in _write_estimator_html(out, estimator, estimator_label, estimator_label_details, is_fitted_css_class, is_fitted_icon, first_call, param_prefix)
    384 elif est_block.kind == "single":
    385     if hasattr(estimator, "_get_params_html"):
--> [386](https://file+.vscode-resource.vscode-cdn.net/Users/martin/dev/pysal/esda/~/dev/pysal/.pixi/envs/default/lib/python3.11/site-packages/sklearn/utils/_repr_html/estimator.py:386)         params = estimator._get_params_html()._repr_html_inner()
    387     else:
    388         params = ""

File ~/dev/pysal/.pixi/envs/default/lib/python3.11/site-packages/sklearn/base.py:312, in BaseEstimator._get_params_html(self, deep)
    308 ordered_out = {name: out[name] for name in init_default_params if name in out}
    309 ordered_out.update({name: out[name] for name in remaining_params})
    311 non_default_ls = tuple(
--> [312](https://file+.vscode-resource.vscode-cdn.net/Users/martin/dev/pysal/esda/~/dev/pysal/.pixi/envs/default/lib/python3.11/site-packages/sklearn/base.py:312)     [name for name, value in ordered_out.items() if is_non_default(name, value)]
    313 )
    315 return ParamsDict(ordered_out, non_default=non_default_ls)

File ~/dev/pysal/.pixi/envs/default/lib/python3.11/site-packages/sklearn/base.py:312, in <listcomp>(.0)
    308 ordered_out = {name: out[name] for name in init_default_params if name in out}
    309 ordered_out.update({name: out[name] for name in remaining_params})
    311 non_default_ls = tuple(
--> [312](https://file+.vscode-resource.vscode-cdn.net/Users/martin/dev/pysal/esda/~/dev/pysal/.pixi/envs/default/lib/python3.11/site-packages/sklearn/base.py:312)     [name for name, value in ordered_out.items() if is_non_default(name, value)]
    313 )
    315 return ParamsDict(ordered_out, non_default=non_default_ls)

File ~/dev/pysal/.pixi/envs/default/lib/python3.11/site-packages/sklearn/base.py:295, in BaseEstimator._get_params_html.<locals>.is_non_default(param_name, param_value)
    291 if isinstance(param_value, BaseEstimator) and type(param_value) is not type(
    292     init_default_params[param_name]
    293 ):
    294     return True
--> [295](https://file+.vscode-resource.vscode-cdn.net/Users/martin/dev/pysal/esda/~/dev/pysal/.pixi/envs/default/lib/python3.11/site-packages/sklearn/base.py:295) if not np.array_equal(
    296     param_value, init_default_params[param_name]
    297 ) and not (
    298     is_scalar_nan(init_default_params[param_name])
    299     and is_scalar_nan(param_value)
    300 ):
    301     return True
    303 return False

File ~/dev/pysal/.pixi/envs/default/lib/python3.11/site-packages/numpy/_core/numeric.py:2590, in array_equal(a1, a2, equal_nan)
   2588     return False
   2589 if not equal_nan:
-> [2590](https://file+.vscode-resource.vscode-cdn.net/Users/martin/dev/pysal/esda/~/dev/pysal/.pixi/envs/default/lib/python3.11/site-packages/numpy/_core/numeric.py:2590)     return builtins.bool((asanyarray(a1 == a2)).all())
   2592 if a1 is a2:
   2593     # nan will compare equal so an array will compare equal to itself.
   2594     return True

File ~/dev/pysal/libpysal/libpysal/graph/_set_ops.py:28, in SetOpsMixin.__eq__(self, other)
     27 def __eq__(self, other):  # ==
---> [28](https://file+.vscode-resource.vscode-cdn.net/Users/martin/dev/pysal/esda/~/dev/pysal/libpysal/libpysal/graph/_set_ops.py:28)     return self.equals(other)

File ~/dev/pysal/libpysal/libpysal/graph/_set_ops.py:182, in SetOpsMixin.equals(self, right)
    169 """
    170 Check that two graphs are identical. This reqiures them to have
    171 1. the same edge labels and node labels
   (...)    178 (focal, neighbor, weight) for the two graphs are the same.
    179 """
    180 try:
    181     pandas.testing.assert_series_equal(
--> [182](https://file+.vscode-resource.vscode-cdn.net/Users/martin/dev/pysal/esda/~/dev/pysal/libpysal/libpysal/graph/_set_ops.py:182)         self._adjacency, right._adjacency, check_dtype=False
    183     )
    184 except AssertionError:
    185     return False

AttributeError: 'NoneType' object has no attribute '_adjacency'
```

This works fine in sklearn 1.6.1.
